ALTER TABLE pipeline_runs
  ADD COLUMN IF NOT EXISTS publish_eligible_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS blocked_by_quality INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS needs_review_count INTEGER NOT NULL DEFAULT 0;
